spring:
  profiles:
    active: prod
  application:
    name: ToDoList
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/Sao_Paulo

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}